In [28]:
!pip install -q groq PyPDF2

In [29]:
from groq import Groq
import PyPDF2
from google.colab import files

In [30]:
GROQ_API_KEY = "your-api-key"

client = Groq(api_key=GROQ_API_KEY)

In [31]:
uploaded = files.upload()

Saving archive (5).zip to archive (5) (1).zip

In [32]:
import zipfile

zip_name = list(uploaded.keys())[0]

with zipfile.ZipFile(zip_name, 'r') as zip_ref:
    zip_ref.extractall("jobs_data")

print("ZIP extracted successfully.")

ZIP extracted successfully.

In [33]:
import os

for root, dirs, files in os.walk("jobs_data"):
    for file in files:
        print(os.path.join(root, file))

jobs_data/naukri_com-job_sample.csv

In [34]:
csv_file = None

for root, dirs, files in os.walk("jobs_data"):
    for file in files:
        if file.endswith(".csv"):
            csv_file = os.path.join(root, file)
            break

print(csv_file)

jobs_data/naukri_com-job_sample.csv

In [35]:
import pandas as pd

df = pd.read_csv(csv_file)

df.head()

,company,education,experience,industry,jobdescription,jobid,joblocation_address,jobtitle,numberofpositions,payrate,postdate,site_name,skills,uniq_id
0,MM Media Pvt Ltd,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,0 - 1 yrs,Media / Entertainment / Internet,Job Description Send me Jobs like this Quali...,210516002263,Chennai,Walkin Data Entry Operator (night Shift),NaN,"1,50,000 - 2,25,000 P.A",2016-05-21 19:30:00 +0000,NaN,ITES,43b19632647068535437c774b6ca6cf8
1,find live infotech,UG: B.Tech/B.E. - Any Specialization PG:MBA/PG...,0 - 0 yrs,Advertising / PR / MR / Event Management,Job Description Send me Jobs like this Quali...,210516002391,Chennai,Work Based Onhome Based Part Time.,60.0,"1,50,000 - 2,50,000 P.A. 20000",2016-05-21 19:30:00 +0000,NaN,Marketing,d4c72325e57f89f364812b5ed5a795f0
2,Softtech Career Infosystem Pvt. Ltd,UG: Any Graduate - Any Specialization PG:Any P...,4 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this - as ...,101016900534,Bengaluru,Pl/sql Developer - SQL,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,c47df6f4cfdf5b46f1fd713ba61b9eba
3,Onboard HRServices LLP,UG: Any Graduate - Any Specialization PG:CA Do...,11 - 15 yrs,Banking / Financial Services / Broking,Job Description Send me Jobs like this - Inv...,81016900536,"Mumbai, Bengaluru, Kolkata, Chennai, Coimbator...",Manager/ad/partner - Indirect Tax - CA,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,Accounts,115d28f140f694dd1cc61c53d03c66ae
4,Spire Technologies and Solutions Pvt. Ltd.,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,6 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Pleas...,120916002122,Bengaluru,JAVA Technical Lead (6-8 yrs) -,4.0,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,a12553fc03bc7bcced8b1bb8963f97b4

In [36]:
print(df.columns)

Index(['company', 'education', 'experience', 'industry', 'jobdescription',
       'jobid', 'joblocation_address', 'jobtitle', 'numberofpositions',
       'payrate', 'postdate', 'site_name', 'skills', 'uniq_id'],
      dtype='object')

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22000 entries, 0 to 21999
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   company              21996 non-null  object
 1   education            20004 non-null  object
 2   experience           21996 non-null  object
 3   industry             21995 non-null  object
 4   jobdescription       21996 non-null  object
 5   jobid                22000 non-null  int64
 6   joblocation_address  21499 non-null  object
 7   jobtitle             22000 non-null  object
 8   numberofpositions    4464 non-null   float64
 9   payrate              21903 non-null  object
 10  postdate             21977 non-null  object
 11  site_name            3987 non-null   object
 12  skills               21472 non-null  object
 13  uniq_id              22000 non-null  object
dtypes: float64(1), int64(1), object(12)
memory usage: 2.3+ MB

In [38]:
df.isnull().sum()

company                    4
education               1996
experience                 4
industry                   5
jobdescription             4
jobid                      0
joblocation_address      501
jobtitle                   0
numberofpositions      17536
payrate                   97
postdate                  23
site_name              18013
skills                   528
uniq_id                    0
dtype: int64

In [39]:
df.head()

,company,education,experience,industry,jobdescription,jobid,joblocation_address,jobtitle,numberofpositions,payrate,postdate,site_name,skills,uniq_id
0,MM Media Pvt Ltd,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,0 - 1 yrs,Media / Entertainment / Internet,Job Description Send me Jobs like this Quali...,210516002263,Chennai,Walkin Data Entry Operator (night Shift),NaN,"1,50,000 - 2,25,000 P.A",2016-05-21 19:30:00 +0000,NaN,ITES,43b19632647068535437c774b6ca6cf8
1,find live infotech,UG: B.Tech/B.E. - Any Specialization PG:MBA/PG...,0 - 0 yrs,Advertising / PR / MR / Event Management,Job Description Send me Jobs like this Quali...,210516002391,Chennai,Work Based Onhome Based Part Time.,60.0,"1,50,000 - 2,50,000 P.A. 20000",2016-05-21 19:30:00 +0000,NaN,Marketing,d4c72325e57f89f364812b5ed5a795f0
2,Softtech Career Infosystem Pvt. Ltd,UG: Any Graduate - Any Specialization PG:Any P...,4 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this - as ...,101016900534,Bengaluru,Pl/sql Developer - SQL,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,c47df6f4cfdf5b46f1fd713ba61b9eba
3,Onboard HRServices LLP,UG: Any Graduate - Any Specialization PG:CA Do...,11 - 15 yrs,Banking / Financial Services / Broking,Job Description Send me Jobs like this - Inv...,81016900536,"Mumbai, Bengaluru, Kolkata, Chennai, Coimbator...",Manager/ad/partner - Indirect Tax - CA,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,Accounts,115d28f140f694dd1cc61c53d03c66ae
4,Spire Technologies and Solutions Pvt. Ltd.,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,6 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Pleas...,120916002122,Bengaluru,JAVA Technical Lead (6-8 yrs) -,4.0,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,a12553fc03bc7bcced8b1bb8963f97b4

In [40]:
!pip install -q groq

In [41]:
from groq import Groq

In [42]:
GROQ_API_KEY = "your-api-key"

client = Groq(api_key=GROQ_API_KEY)

In [43]:
def naukri_ai(question):

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",

        messages=[
            {
                "role":"system",
                "content":"""
                You are an AI Job Recommendation Chatbot.

                Your tasks are:

                - Recommend jobs.
                - Suggest suitable roles.
                - Suggest skills.
                - Explain job descriptions.
                - Compare jobs.
                - Suggest certifications.
                - Suggest salary expectations.
                - Suggest interview questions.
                - Help freshers find suitable jobs.
                """
            },

            {
                "role":"user",
                "content":f"""

                JOB DATASET:

                {jobs_text}


                USER QUESTION:

                {question}

                """
            }

        ],

        temperature=0.5,
        max_tokens=1500

    )

    return response.choices[0].message.content

In [45]:
def search_jobs(keyword):

    keyword = keyword.lower()

    results = df[df.astype(str).apply(
        lambda x: x.str.lower().str.contains(keyword)
    ).any(axis=1)]

    return results

In [46]:
def naukri_ai(question):

    jobs = search_jobs(question)

    if jobs.empty:
        return "No matching jobs found."

    jobs_text = jobs.head(10).to_string(index=False)

    response = client.chat.completions.create(

        model="llama-3.3-70b-versatile",

        messages=[

            {
                "role":"system",
                "content":"You are an AI Job Recommendation Assistant."
            },

            {
                "role":"user",
                "content":f"""

                The following jobs were found:

                {jobs_text}

                Explain and recommend the most suitable jobs.
                """
            }

        ],

        temperature=0.5,
        max_tokens=1000

    )

    return response.choices[0].message.content

In [ ]:
while True:

    question = input("Ask Naukri AI : ")

    if question.lower() == "exit":
        break

    print(naukri_ai(question))

Ask Naukri AI : pyhon job
No matching jobs found.
Ask Naukri AI : jobs
Based on the provided job listings, I will analyze and recommend the most suitable jobs.

**Job 1: Walkin Data Entry Operator (Night Shift) at MM Media Pvt Ltd**

* Education: UG: B.Tech/B.E. - Any Specialization, PG: Any Postgraduate - Any Specialization
* Experience: 0-1 year
* Industry: Media / Entertainment / Internet
* Skills: Basic Computer Knowledge, English Typing, Data Entry
* Salary: INR 1,50,000 - 2,25,000 P.A

This job is suitable for freshers with basic computer knowledge and English typing skills. The job involves data entry work, and the company provides a decent salary package.

**Job 2: Work Based On Home Based Part Time at Find Live Infotech**

* Education: UG: B.Tech/B.E. - Any Specialization, PG: MBA/PGDM - Any Specialization
* Experience: 0-0 years (freshers)
* Industry: Advertising / PR / MR / Event Management
* Skills: Basic Computer Knowledge, English Typing, Data Entry
* Salary: INR 1,50,000 - 2,50,000 P.A

This job is similar to Job 1, with a focus on part-time work from home. The company provides a flexible work arrangement, and the salary package is similar to Job 1.

**Job 3: PL/SQL Developer at Softtech Career Infosystem Pvt. Ltd**

* Education: UG: Any Graduate - Any Specialization, PG: Any Postgraduate - Any Specialization
* Experience: 4-8 years
* Industry: IT-Software / Software Services
* Skills: PL/SQL, SQL Loader, Application Development
* Salary: Not Disclosed by Recruiter

This job is suitable for experienced professionals with expertise in PL/SQL and SQL Loader. The company is looking for a skilled developer to work on application development projects.

**Job 4: Manager/AD - Indirect Tax at Onboard HRServices LLP**

* Education: UG: Any Graduate - Any Specialization, PG: CA - Any Specialization
* Experience: 11-15 years
* Industry: Banking / Financial Services / Broking
* Skills: Indirect Taxation, Service Tax, Central Excise
* Salary: Not Disclosed by Recruiter

This job is suitable for experienced professionals with expertise in indirect taxation, service tax, and central excise. The company is looking for a manager to lead the indirect tax team.

**Job 5: JAVA Technical Lead at Spire Technologies and Solutions Pvt. Ltd**

* Education: UG: B.Tech/B.E. - Any Specialization, PG: Any Postgraduate - Any Specialization
* Experience: 6-8 years
* Industry: IT-Software / Software Services
* Skills: Java, J2EE, Web Services, Agile Methodology
* Salary: Not Disclosed by Recruiter

This job is suitable for experienced professionals with expertise in Java, J2EE, and web services. The company is looking for a technical lead to lead the development team.

**Job 6: AS400 Developer at PFS Web Global Services Pvt Ltd**

* Education: UG: B.Tech/B.E. - Any Specialization, PG: MCA - Computers, M.Tech - Any Specialization
* Experience: 2-5 years
* Industry: IT-Software / Software Services
* Skills: AS400, RPG, JD Edwards
* Salary: Not Disclosed by Recruiter

This job is suitable for experienced professionals with expertise in AS400, RPG, and JD Edwards. The company is looking for a developer to work on application development projects.

**Job 7: PHP Developer at Kinesis Management Consultant Pvt. Ltd**

* Education: UG: Diploma - Any Specialization, Electrical, Electronics/Telecommunication
* Experience: 2-7 years
* Industry: IT-Software / Software Services
* Skills: PHP, MySQL, JQuery, Ajax
* Salary: INR 3,00,000 - 6,50,000 P.A

This job is suitable for experienced professionals with expertise in PHP, MySQL, JQuery, and Ajax. The company is looking for a developer to work on web application development projects.

**Job 8: Member Technical Staff - Wire Harness at Agile HR consultancy Pvt. Ltd**

* Education: UG: Diploma - Any Specialization, Electrical, Electronics/Telecommunication
* Experience: 2-10 years
* Industry: Aviation / Aerospace Firms
* Skills: Wire Harness, Cable Harness, Aircraft Looms
* Salary: Not Disclosed by Recruiter

This job is suitable for experienced professionals with expertise in wire harness, cable harness, and aircraft looms. The company is looking for